# mlrose_hiive Tutorial Examples - Genevieve Hayes

## Overview

mlrose_hiive is a Python package for applying some of the most common randomized optimization and search algorithms to a range of different optimization problems, over both discrete- and continuous-valued parameter spaces. This notebook contains the examples used in the mlrose_hiive tutorial.

### Import Libraries

In [1]:
! pip install networkx
! python --version

import mlrose_hiive
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.metrics import accuracy_score

Python 3.9.12


### Example 6: Fitting a Neural Network to the Iris Dataset

In [42]:
# Load the Iris dataset
data = load_iris()

In [43]:
# Get feature values of first observation
print(data.data[0])

[5.1 3.5 1.4 0.2]


In [44]:
# Get feature names
print(data.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [45]:
# Get target value of first observation
print(data.target[0])

0


In [46]:
# Get target name of first observation
print(data.target_names[data.target[0]])

setosa


In [47]:
# Get minimum feature values
print(np.min(data.data, axis = 0))

[4.3 2.  1.  0.1]


In [48]:
# Get maximum feature values
print(np.max(data.data, axis = 0))

[7.9 4.4 6.9 2.5]


In [49]:
# Get unique target values
print(np.unique(data.target))

[0 1 2]


In [50]:
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size = 0.2, 
                                                    random_state = 3)

In [51]:
# Normalize feature data
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [52]:
# One hot encode target values
one_hot = OneHotEncoder()

y_train_hot = one_hot.fit_transform(y_train.reshape(-1, 1)).todense()
y_test_hot = one_hot.transform(y_test.reshape(-1, 1)).todense()

In [53]:
# Initialize neural network object and fit object - attempt 1
nn_model1 = mlrose_hiive.NeuralNetwork(hidden_nodes = [2], activation ='relu', 
                                 algorithm ='random_hill_climb', 
                                 max_iters = 1000, bias = True, is_classifier = True, 
                                 learning_rate = 0.0001, early_stopping = True, 
                                 clip_max = 5, max_attempts = 100, random_state = 3)

nn_model1.fit(X_train_scaled, y_train_hot)

NeuralNetwork(clip_max=5, early_stopping=True, hidden_nodes=[2],
              learning_rate=0.0001, max_attempts=100, max_iters=1000,
              random_state=3)

In [54]:
# Predict labels for train set and assess accuracy
y_train_pred = nn_model1.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)

0.45


In [55]:
# Predict labels for test set and assess accuracy
y_test_pred = nn_model1.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.5333333333333333


In [56]:
# Initialize neural network object and fit object - attempt 2
nn_model2 = mlrose_hiive.NeuralNetwork(hidden_nodes = [2], activation = 'relu', 
                                 algorithm = 'gradient_descent', 
                                 max_iters = 1000, bias = True, is_classifier = True, 
                                 learning_rate = 0.0001, early_stopping = True, 
                                 clip_max = 5, max_attempts = 100, random_state = 3)

nn_model2.fit(X_train_scaled, y_train_hot)

NeuralNetwork(algorithm='gradient_descent', clip_max=5, early_stopping=True,
              hidden_nodes=[2], learning_rate=0.0001, max_attempts=100,
              max_iters=1000, random_state=3)

In [57]:
# Predict labels for train set and assess accuracy
y_train_pred = nn_model2.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)

0.625


In [58]:
# Predict labels for test set and assess accuracy
y_test_pred = nn_model2.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.5666666666666667


### Example 8: Fitting a Logistic Regression to the Iris Data using the NeuralNetwork() class

In [65]:
# Initialize neural network object and fit object - attempt 1
lr_nn_model1 = mlrose_hiive.NeuralNetwork(hidden_nodes = [], activation = 'sigmoid', 
                                    algorithm = 'random_hill_climb', 
                                    max_iters = 1000, bias = True, is_classifier = True, 
                                    learning_rate = 0.0001, early_stopping = True, 
                                    clip_max = 5, max_attempts = 100, random_state = 3)

lr_nn_model1.fit(X_train_scaled, y_train_hot)

NeuralNetwork(activation='sigmoid', clip_max=5, early_stopping=True,
              hidden_nodes=[], learning_rate=0.0001, max_attempts=100,
              max_iters=1000, random_state=3)

In [66]:
# Predict labels for train set and assess accuracy
y_train_pred = lr_nn_model1.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)

0.19166666666666668


In [67]:
# Predict labels for test set and assess accuracy
y_test_pred = lr_nn_model1.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.06666666666666667


In [68]:
# Initialize neural network object and fit object - attempt 2
lr_nn_model2 = mlrose_hiive.NeuralNetwork(hidden_nodes = [], activation = 'sigmoid', 
                                    algorithm = 'random_hill_climb', 
                                    max_iters = 1000, bias = True, is_classifier = True, 
                                    learning_rate = 0.01, early_stopping = True, 
                                    clip_max = 5, max_attempts = 100, random_state = 3)

lr_nn_model2.fit(X_train_scaled, y_train_hot)

NeuralNetwork(activation='sigmoid', clip_max=5, early_stopping=True,
              hidden_nodes=[], learning_rate=0.01, max_attempts=100,
              max_iters=1000, random_state=3)

In [69]:
# Predict labels for train set and assess accuracy
y_train_pred = lr_nn_model2.predict(X_train_scaled)

y_train_accuracy = accuracy_score(y_train_hot, y_train_pred)

print(y_train_accuracy)

0.6833333333333333


In [70]:
# Predict labels for test set and assess accuracy
y_test_pred = lr_nn_model2.predict(X_test_scaled)

y_test_accuracy = accuracy_score(y_test_hot, y_test_pred)

print(y_test_accuracy)

0.7


## Flipflop Problem Implementations

In [160]:
# Initialize fitness function object using pre-defined class FlipFlop
fitness = mlrose_hiive.FlipFlop()

In [161]:
# Define optimization problem object
SIZE = 32
problem = mlrose_hiive.DiscreteOpt(length = SIZE, fitness_fn = fitness, maximize=True, max_val=2)

### Random Hill Climbing

In [162]:
# Solve using randomized hill climbing - attempt 1 (1 random attempt)
init_state = np.zeros(32)
best_state, best_fitness, fitness_curve = mlrose_hiive.random_hill_climb(problem, max_attempts=1, max_iters=10, restarts=1, init_state=init_state, curve=True, random_state=1)
print(fitness_curve)

[[2. 2.]
 [4. 4.]
 [4. 5.]]


In [249]:
print('The best state found is: ', best_state)

The best state found is:  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


In [250]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  4.0


In [164]:
# Solve using randomized hill climbing - attempt 2 (10 random attempts)
init_state = np.zeros(32)
best_state, best_fitness, fitness_curve = mlrose_hiive.random_hill_climb(problem, max_attempts=1, max_iters=10, restarts=10, init_state=init_state, curve=True, random_state=1)
print(fitness_curve)

[[  2. 127.]
 [  4. 129.]
 [  6. 131.]
 [  8. 133.]
 [ 10. 135.]
 [ 12. 137.]
 [ 12. 138.]]


In [252]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  12.0


In [253]:
print('The best state found is: ', best_state)

The best state found is:  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.
 0. 1. 0. 0. 1. 0. 1. 0.]


### Simulated Annealing implementation

In [254]:
# Define decay schedule
schedule = mlrose_hiive.ExpDecay()

In [165]:
# Solve using simulated annealing - attempt 1 (maximum 10 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.simulated_annealing(problem, schedule = schedule, max_attempts = 10, 
                                                      max_iters = 10, init_state = init_state,
                                                      random_state = 1, curve=True)
print(fitness_curve)

[[  2. 191.]
 [  4. 193.]
 [  4. 195.]
 [  6. 197.]
 [  6. 199.]
 [  7. 201.]
 [  9. 203.]
 [  9. 205.]
 [  9. 207.]
 [ 11. 209.]]


In [256]:
print('The best state found is: ', best_state)

The best state found is:  [1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0.]


In [257]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  11.0


In [166]:
# Solve using simulated annealing - attempt 2 (maximum 100 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.simulated_annealing(problem, schedule = schedule, max_attempts = 10, 
                                                      max_iters = 100, init_state = init_state,  curve = True,
                                                      random_state = 1)
print(fitness_curve)

[[  2. 212.]
 [  4. 214.]
 [  4. 216.]
 [  6. 218.]
 [  6. 220.]
 [  7. 222.]
 [  9. 224.]
 [  9. 226.]
 [  9. 228.]
 [ 11. 230.]
 [ 13. 232.]
 [ 15. 234.]
 [ 17. 236.]
 [ 17. 237.]
 [ 17. 239.]
 [ 19. 241.]
 [ 19. 242.]
 [ 19. 244.]
 [ 19. 245.]
 [ 19. 246.]
 [ 19. 248.]
 [ 21. 250.]
 [ 20. 252.]
 [ 20. 253.]
 [ 20. 254.]
 [ 20. 256.]
 [ 20. 258.]
 [ 18. 260.]
 [ 18. 262.]
 [ 18. 263.]
 [ 20. 265.]
 [ 20. 267.]
 [ 20. 269.]
 [ 20. 271.]
 [ 20. 273.]
 [ 21. 275.]
 [ 21. 276.]
 [ 21. 277.]
 [ 21. 279.]
 [ 23. 281.]
 [ 23. 283.]
 [ 23. 285.]
 [ 23. 286.]
 [ 23. 288.]
 [ 25. 290.]
 [ 24. 292.]
 [ 24. 294.]
 [ 24. 296.]
 [ 24. 297.]
 [ 24. 299.]
 [ 26. 301.]
 [ 26. 302.]
 [ 26. 304.]
 [ 27. 306.]
 [ 27. 307.]
 [ 27. 308.]
 [ 27. 309.]
 [ 27. 310.]
 [ 27. 311.]
 [ 27. 312.]
 [ 27. 313.]
 [ 27. 314.]
 [ 27. 315.]
 [ 27. 316.]]


In [259]:
print('The best state found is: ', best_state)

The best state found is:  [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 1.]


In [260]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  27.0


### Genetic Algorithm

In [169]:
# Solve using simulated annealing - attempt 1 (maximum 10 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.genetic_alg(problem, pop_size=10, mutation_prob=0.1, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ 19.  22.]
 [ 19.  33.]
 [ 21.  45.]
 [ 21.  56.]
 [ 21.  67.]
 [ 21.  78.]
 [ 21.  89.]
 [ 21. 100.]
 [ 21. 111.]
 [ 21. 122.]]


In [262]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0]


In [263]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  21.0


In [170]:
# Solve using simulated annealing - attempt 2 (maximum 20 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.genetic_alg(problem, pop_size=10, mutation_prob=0.1, max_attempts=10, max_iters=20, curve=True, random_state=1)
print(fitness_curve)

[[ 19.  22.]
 [ 19.  33.]
 [ 21.  45.]
 [ 21.  56.]
 [ 21.  67.]
 [ 21.  78.]
 [ 21.  89.]
 [ 21. 100.]
 [ 21. 111.]
 [ 21. 122.]
 [ 23. 134.]
 [ 23. 145.]
 [ 23. 156.]
 [ 23. 167.]
 [ 23. 178.]
 [ 24. 190.]
 [ 24. 201.]
 [ 24. 212.]
 [ 24. 223.]
 [ 24. 234.]]


In [265]:
print('The best state found is: ', best_state)

The best state found is:  [0 0 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 0]


In [266]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  24.0


### MIMIC

In [171]:
# Solve using simulated annealing - attempt 1 (population size 20, maximum 10 attempts, maximum 10 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=20, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ 23.  42.]
 [ 23.  63.]
 [ 23.  84.]
 [ 23. 105.]
 [ 23. 126.]
 [ 23. 147.]
 [ 23. 168.]
 [ 23. 189.]
 [ 23. 210.]
 [ 23. 231.]]


In [268]:
print('The best state found is: ', best_state)

The best state found is:  [0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1]


In [269]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  23.0


In [172]:
# Solve using simulated annealing - attempt 2 (population size 20, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=20, keep_pct=0.2, max_attempts=100, max_iters=100, curve=True, random_state=1)
print(fitness_curve)

[[  23.   42.]
 [  23.   63.]
 [  23.   84.]
 [  23.  105.]
 [  23.  126.]
 [  23.  147.]
 [  23.  168.]
 [  23.  189.]
 [  23.  210.]
 [  23.  231.]
 [  23.  252.]
 [  23.  273.]
 [  23.  294.]
 [  23.  315.]
 [  23.  336.]
 [  23.  357.]
 [  23.  378.]
 [  23.  399.]
 [  23.  420.]
 [  23.  441.]
 [  23.  462.]
 [  23.  483.]
 [  23.  504.]
 [  23.  525.]
 [  23.  546.]
 [  23.  567.]
 [  23.  588.]
 [  23.  609.]
 [  23.  630.]
 [  23.  651.]
 [  23.  672.]
 [  23.  693.]
 [  23.  714.]
 [  23.  735.]
 [  23.  756.]
 [  23.  777.]
 [  23.  798.]
 [  23.  819.]
 [  23.  840.]
 [  23.  861.]
 [  23.  882.]
 [  23.  903.]
 [  23.  924.]
 [  23.  945.]
 [  23.  966.]
 [  23.  987.]
 [  23. 1008.]
 [  23. 1029.]
 [  23. 1050.]
 [  23. 1071.]
 [  23. 1092.]
 [  23. 1113.]
 [  23. 1134.]
 [  23. 1155.]
 [  23. 1176.]
 [  23. 1197.]
 [  23. 1218.]
 [  23. 1239.]
 [  23. 1260.]
 [  23. 1281.]
 [  23. 1302.]
 [  23. 1323.]
 [  23. 1344.]
 [  23. 1365.]
 [  23. 1386.]
 [  23. 1407.]
 [  23. 14

In [173]:
print('The best state found is: ', best_state)

The best state found is:  [0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1]


In [174]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  23.0


In [175]:
# Solve using simulated annealing - attempt 3 (population size 40, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=40, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ 23.  82.]
 [ 25. 124.]
 [ 25. 165.]
 [ 25. 206.]
 [ 25. 247.]
 [ 25. 288.]
 [ 25. 329.]
 [ 25. 370.]
 [ 25. 411.]
 [ 25. 452.]]


In [274]:
print('The best state found is: ', best_state)

The best state found is:  [1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0]


In [275]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  25.0


In [176]:
# Solve using simulated annealing - attempt 4 (population size 100, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=100, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[  23.  202.]
 [  23.  303.]
 [  23.  404.]
 [  25.  506.]
 [  25.  607.]
 [  27.  709.]
 [  27.  810.]
 [  27.  911.]
 [  27. 1012.]
 [  27. 1113.]]


In [277]:
print('The best state found is: ', best_state)

The best state found is:  [0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1]


In [278]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  27.0


In [177]:
# Solve using simulated annealing - attempt 5 (population size 200, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(SIZE)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[  27.  402.]
 [  27.  603.]
 [  28.  805.]
 [  30. 1007.]
 [  30. 1208.]
 [  30. 1409.]
 [  30. 1610.]
 [  30. 1811.]
 [  30. 2012.]
 [  30. 2213.]]


In [280]:
print('The best state found is: ', best_state)

The best state found is:  [1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [281]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  30.0


## Traveling Salesman Problem (TSP) Using Coordinate-Defined Fitness Function

In [179]:
rng = np.random.default_rng(1)

# Create list of city coordinates
CITIES = 8
coordinates = rng.integers(low=0, high=CITIES, size=(CITIES,2))
coords_list = [(c[0], c[1]) for c in coordinates]
print(coords_list)

# Initialize fitness function object using coords_list
fitness_coords = mlrose_hiive.TravellingSales(coords = coords_list)

[(3, 4), (6, 7), (0, 1), (6, 7), (1, 2), (6, 3), (2, 6), (2, 3)]


In [180]:
# Define optimization problem object
problem = mlrose_hiive.TSPOpt(length = 8, fitness_fn = fitness_coords, maximize = True)

### Randomized Hill Climbing

In [181]:
# Solve using randomized hill climbing - attempt 1 (1 random attempt)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.random_hill_climb(problem, max_attempts=10, max_iters=10, restarts=1, init_state=init_state, curve=True, random_state=1)
print(fitness_curve)

[[-42.35424201   2.        ]
 [-31.04053351   4.        ]
 [-31.04053351   5.        ]
 [-31.00401013   7.        ]
 [-27.99743742   9.        ]
 [-27.99743742  10.        ]
 [-27.99743742  11.        ]
 [-25.1690103   13.        ]
 [-25.1690103   14.        ]
 [-25.1690103   15.        ]]


In [11]:
print('The best state found is: ', best_state)

The best state found is:  [5 1 3 7 0 6 4 2]


In [12]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -25.16901029769278


In [182]:
# Solve using randomized hill climbing - attempt 2 (10 random attempts)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.random_hill_climb(problem, max_attempts=10, max_iters=10, restarts=10, init_state=init_state, curve=True, random_state=1)
print(fitness_curve)

[[-34.627417   168.        ]
 [-34.627417   169.        ]
 [-31.17758197 171.        ]
 [-22.6923006  173.        ]
 [-22.6923006  174.        ]
 [-22.6923006  175.        ]
 [-22.6923006  176.        ]
 [-22.6923006  177.        ]
 [-22.6923006  178.        ]
 [-22.6923006  179.        ]]


In [14]:
print('The best state found is: ', best_state)

The best state found is:  [0 6 2 4 7 5 1 3]


In [15]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -22.69230059649977


### Simulated Annealing implementation

In [17]:
# Define decay schedule
schedule = mlrose_hiive.ExpDecay()

In [184]:
# Solve using simulated annealing - attempt 1 (maximum 10 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.simulated_annealing(problem, schedule = schedule, max_attempts = 10, 
                                                      max_iters = 10, init_state = init_state, curve=True,
                                                      random_state = 1)
print(fitness_curve)

[[-42.35424201 182.        ]
 [-31.04053351 184.        ]
 [-31.04053351 186.        ]
 [-28.0339608  188.        ]
 [-28.0339608  189.        ]
 [-28.0339608  190.        ]
 [-28.0339608  191.        ]
 [-28.0339608  192.        ]
 [-28.0339608  193.        ]
 [-28.0339608  194.        ]]


In [20]:
print('The best state found is: ', best_state)

The best state found is:  [7 1 3 5 4 0 6 2]


In [21]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -28.03396079721184


In [185]:
# Solve using simulated annealing - attempt 2 (maximum 100 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.simulated_annealing(problem, schedule = schedule, max_attempts = 10, 
                                                      max_iters = 100, init_state = init_state,  curve = True,
                                                      random_state = 1)
print(fitness_curve)

[[-42.35424201 197.        ]
 [-31.04053351 199.        ]
 [-31.04053351 201.        ]
 [-28.0339608  203.        ]
 [-28.0339608  204.        ]
 [-28.0339608  205.        ]
 [-28.0339608  206.        ]
 [-28.0339608  207.        ]
 [-28.0339608  208.        ]
 [-28.0339608  209.        ]
 [-23.96399004 211.        ]
 [-23.96399004 212.        ]
 [-23.96399004 213.        ]
 [-23.96399004 215.        ]
 [-23.96399004 216.        ]
 [-23.96399004 217.        ]
 [-23.96399004 218.        ]
 [-21.43024141 220.        ]
 [-21.43024141 221.        ]
 [-21.43024141 222.        ]
 [-21.43024141 224.        ]
 [-21.43024141 225.        ]
 [-21.43024141 226.        ]
 [-21.43024141 227.        ]
 [-21.43024141 228.        ]
 [-21.43024141 229.        ]
 [-21.43024141 230.        ]
 [-21.43024141 231.        ]
 [-21.43024141 233.        ]
 [-21.43024141 234.        ]
 [-21.43024141 235.        ]
 [-21.43024141 236.        ]
 [-21.43024141 237.        ]
 [-21.3564511  239.        ]
 [-21.3564511 

In [24]:
print('The best state found is: ', best_state)

The best state found is:  [0 5 1 3 6 4 2 7]


In [25]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -21.06534316089608


### Genetic Algorithm

In [186]:
# Solve using simulated annealing - attempt 1 (maximum 10 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.genetic_alg(problem, pop_size=10, mutation_prob=0.1, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[-25.96399004  22.        ]
 [-25.67835776  34.        ]
 [-25.67835776  45.        ]
 [-23.94347449  57.        ]
 [-23.94347449  68.        ]
 [-23.94347449  79.        ]
 [-23.94347449  90.        ]
 [-23.94347449 101.        ]
 [-23.94347449 112.        ]
 [-23.94347449 123.        ]]


In [29]:
print('The best state found is: ', best_state)

The best state found is:  [5 4 7 2 0 6 3 1]


In [30]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -23.943474490948805


In [187]:
# Solve using simulated annealing - attempt 2 (maximum 20 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.genetic_alg(problem, pop_size=10, mutation_prob=0.1, max_attempts=10, max_iters=20, curve=True, random_state=1)
print(fitness_curve)

[[-25.96399004  22.        ]
 [-25.67835776  34.        ]
 [-25.67835776  45.        ]
 [-23.94347449  57.        ]
 [-23.94347449  68.        ]
 [-23.94347449  79.        ]
 [-23.94347449  90.        ]
 [-23.94347449 101.        ]
 [-23.94347449 112.        ]
 [-23.94347449 123.        ]
 [-22.6923006  135.        ]
 [-22.6923006  146.        ]
 [-22.6923006  157.        ]
 [-22.6923006  168.        ]
 [-22.6923006  179.        ]
 [-22.6923006  190.        ]
 [-22.6923006  201.        ]
 [-22.6923006  212.        ]
 [-22.6923006  223.        ]
 [-22.6923006  234.        ]]


In [33]:
print('The best state found is: ', best_state)

The best state found is:  [5 7 4 2 6 0 1 3]


In [34]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -22.692300596499766


### MIMIC

In [188]:
# Solve using simulated annealing - attempt 1 (population size 20, maximum 10 attempts, maximum 10 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=20, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[-23.4209462  42.       ]
 [-23.4209462  63.       ]
 [-23.4209462  84.       ]
 [-23.4209462 105.       ]
 [-23.4209462 126.       ]
 [-23.4209462 147.       ]
 [-23.4209462 168.       ]
 [-23.4209462 189.       ]
 [-23.4209462 210.       ]
 [-23.4209462 231.       ]]


In [38]:
print('The best state found is: ', best_state)

The best state found is:  [7 3 1 5 0 6 4 2]


In [39]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -23.420946199897497


In [189]:
# Solve using simulated annealing - attempt 2 (population size 20, maximum 100 attempts, maximum 100 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=20, keep_pct=0.2, max_attempts=100, max_iters=100, curve=True, random_state=1)
print(fitness_curve)

[[ -23.4209462   42.       ]
 [ -23.4209462   63.       ]
 [ -23.4209462   84.       ]
 [ -23.4209462  105.       ]
 [ -23.4209462  126.       ]
 [ -23.4209462  147.       ]
 [ -23.4209462  168.       ]
 [ -23.4209462  189.       ]
 [ -23.4209462  210.       ]
 [ -23.4209462  231.       ]
 [ -23.4209462  252.       ]
 [ -23.4209462  273.       ]
 [ -23.4209462  294.       ]
 [ -23.4209462  315.       ]
 [ -23.4209462  336.       ]
 [ -23.4209462  357.       ]
 [ -23.4209462  378.       ]
 [ -23.4209462  399.       ]
 [ -23.4209462  420.       ]
 [ -23.4209462  441.       ]
 [ -23.4209462  462.       ]
 [ -23.4209462  483.       ]
 [ -23.4209462  504.       ]
 [ -23.4209462  525.       ]
 [ -23.4209462  546.       ]
 [ -23.4209462  567.       ]
 [ -23.4209462  588.       ]
 [ -23.4209462  609.       ]
 [ -23.4209462  630.       ]
 [ -23.4209462  651.       ]
 [ -23.4209462  672.       ]
 [ -23.4209462  693.       ]
 [ -23.4209462  714.       ]
 [ -23.4209462  735.       ]
 [ -23.4209462

In [41]:
print('The best state found is: ', best_state)

The best state found is:  [7 3 1 5 0 6 4 2]


In [42]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -23.420946199897497


In [190]:
# Solve using simulated annealing - attempt 3 (population size 40, maximum 100 attempts, maximum 100 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=40, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[-21.3564511  82.       ]
 [-21.3564511 123.       ]
 [-21.3564511 164.       ]
 [-21.3564511 205.       ]
 [-21.3564511 246.       ]
 [-21.3564511 287.       ]
 [-21.3564511 328.       ]
 [-21.3564511 369.       ]
 [-21.3564511 410.       ]
 [-21.3564511 451.       ]]


In [44]:
print('The best state found is: ', best_state)

The best state found is:  [7 6 3 1 5 0 2 4]


In [45]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -21.356451097651515


In [191]:
# Solve using simulated annealing - attempt 4 (population size 100, maximum 100 attempts, maximum 100 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=100, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ -21.11504737  202.        ]
 [ -20.92636961  304.        ]
 [ -20.92636961  405.        ]
 [ -20.92636961  506.        ]
 [ -20.92636961  607.        ]
 [ -20.92636961  708.        ]
 [ -20.92636961  809.        ]
 [ -20.92636961  910.        ]
 [ -20.92636961 1011.        ]
 [ -20.92636961 1112.        ]]


In [47]:
print('The best state found is: ', best_state)

The best state found is:  [1 3 6 0 7 4 2 5]


In [48]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -20.926369610573495


In [192]:
# Solve using simulated annealing - attempt 5 (population size 200, maximum 100 attempts, maximum 100 iterations)
init_state = [i for i in range(0,CITIES)]
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ -21.06534316  402.        ]
 [ -20.92636961  604.        ]
 [ -20.92636961  805.        ]
 [ -20.92636961 1006.        ]
 [ -20.92636961 1207.        ]
 [ -20.92636961 1408.        ]
 [ -20.92636961 1609.        ]
 [ -20.92636961 1810.        ]
 [ -20.92636961 2011.        ]
 [ -20.92636961 2212.        ]]


In [50]:
print('The best state found is: ', best_state)

The best state found is:  [3 6 0 7 4 2 5 1]


In [51]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  -20.926369610573495


## 4-Peaks Problem

In [205]:
# Initialize fitness function object using pre-defined class
fitness = mlrose_hiive.SixPeaks()

In [206]:
# Define optimization problem object
DIMENSIONS = 16
problem = mlrose_hiive.DiscreteOpt(length = DIMENSIONS, fitness_fn = fitness, maximize=True, max_val=2)

### Randomized Hill Climbing

In [207]:
# Solve using randomized hill climbing - attempt 1 (1 random attempt)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.random_hill_climb(problem, max_attempts=10, max_iters=10, restarts=1, init_state=init_state, curve=True, random_state=1)
print(fitness_curve)

[[16.  1.]
 [16.  2.]
 [16.  3.]
 [16.  4.]
 [16.  5.]
 [16.  6.]
 [16.  7.]
 [16.  8.]
 [16.  9.]
 [16. 10.]]


In [208]:
print('The best state found is: ', best_state)

The best state found is:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [209]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  16.0


In [210]:
# Solve using randomized hill climbing - attempt 2 (10 random attempts)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curves = mlrose_hiive.random_hill_climb(problem, max_attempts=10, max_iters=10, restarts=10, init_state=init_state, curve=True, random_state=1)
print(fitness_curves)

[[16. 21.]
 [16. 22.]
 [16. 23.]
 [16. 24.]
 [16. 25.]
 [16. 26.]
 [16. 27.]
 [16. 28.]
 [16. 29.]
 [16. 30.]]


In [211]:
print('The best state found is: ', best_state)

The best state found is:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [212]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  16.0


### Simulated Annealing

In [213]:
# Define decay schedule
schedule = mlrose_hiive.ExpDecay()

In [214]:
# Solve using simulated annealing - attempt 1 (maximum 10 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.simulated_annealing(problem, schedule = schedule, max_attempts = 10, 
                                                      max_iters = 10, init_state = init_state, curve = True,
                                                      random_state = 1)
print(fitness_curve)

[[ 16. 132.]
 [  7. 134.]
 [  7. 135.]
 [  7. 137.]
 [  7. 138.]
 [  7. 139.]
 [  7. 141.]
 [  7. 143.]
 [  7. 144.]
 [  7. 145.]]


In [215]:
print('The best state found is: ', best_state)

The best state found is:  [1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [216]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  7.0


In [217]:
# Solve using simulated annealing - attempt 2 (maximum 100 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.simulated_annealing(problem, schedule = schedule, max_attempts = 10, 
                                                      max_iters = 100, init_state = init_state,  curve = True,
                                                      random_state = 1)
print(fitness_curve)

[[ 16. 147.]
 [  7. 149.]
 [  7. 150.]
 [  7. 152.]
 [  7. 153.]
 [  7. 154.]
 [  7. 156.]
 [  7. 158.]
 [  7. 159.]
 [  7. 160.]
 [  7. 162.]
 [  7. 164.]
 [  7. 166.]
 [  7. 168.]
 [  7. 169.]
 [  7. 170.]
 [  7. 172.]
 [  7. 174.]
 [  7. 175.]
 [  7. 176.]
 [  7. 177.]
 [  7. 179.]
 [  6. 181.]
 [  6. 183.]
 [  6. 184.]
 [  6. 186.]
 [ 10. 188.]
 [ 10. 190.]
 [ 10. 192.]
 [ 10. 194.]
 [ 10. 195.]
 [ 10. 196.]
 [ 10. 197.]
 [ 10. 198.]
 [ 11. 200.]
 [ 11. 201.]
 [ 11. 202.]
 [ 11. 203.]
 [ 11. 204.]
 [ 11. 205.]
 [ 11. 206.]
 [ 11. 208.]
 [ 11. 209.]
 [ 11. 210.]
 [ 11. 211.]
 [ 11. 212.]
 [ 11. 213.]
 [ 11. 214.]
 [ 11. 215.]
 [ 11. 216.]
 [ 15. 218.]
 [ 15. 219.]
 [ 15. 220.]
 [ 15. 221.]
 [ 15. 222.]
 [ 15. 223.]
 [ 15. 224.]
 [ 15. 225.]
 [ 15. 226.]
 [ 15. 227.]
 [ 15. 228.]]


In [218]:
print('The best state found is: ', best_state)

The best state found is:  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [219]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  15.0


### Genetic Algorithm

In [220]:
# Solve using simulated annealing - attempt 1 (maximum 10 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.genetic_alg(problem, pop_size=10, mutation_prob=0.1, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[  6.  22.]
 [ 19.  34.]
 [ 21.  46.]
 [ 21.  57.]
 [ 21.  68.]
 [ 21.  79.]
 [ 21.  90.]
 [ 21. 101.]
 [ 21. 112.]
 [ 21. 123.]]


In [221]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0]


In [222]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  21.0


In [223]:
# Solve using simulated annealing - attempt 2 (maximum 20 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.genetic_alg(problem, pop_size=10, mutation_prob=0.1, max_attempts=10, max_iters=20, curve=True, random_state=1)
print(fitness_curve)

[[  6.  22.]
 [ 19.  34.]
 [ 21.  46.]
 [ 21.  57.]
 [ 21.  68.]
 [ 21.  79.]
 [ 21.  90.]
 [ 21. 101.]
 [ 21. 112.]
 [ 21. 123.]
 [ 21. 134.]
 [ 21. 145.]
 [ 21. 156.]]


In [141]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0]


In [142]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  21.0


### MIMIC

In [224]:
# Solve using simulated annealing - attempt 1 (population size 20, maximum 10 attempts, maximum 10 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=20, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ 22.  42.]
 [ 22.  63.]
 [ 22.  84.]
 [ 22. 105.]
 [ 22. 126.]
 [ 22. 147.]
 [ 22. 168.]
 [ 22. 189.]
 [ 22. 210.]
 [ 22. 231.]]


In [144]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0]


In [145]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  22.0


In [226]:
# Solve using simulated annealing - attempt 2 (population size 20, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=20, keep_pct=0.2, max_attempts=100, max_iters=100, curve=True, random_state=1)
print(fitness_curve)

[[  22.   42.]
 [  22.   63.]
 [  22.   84.]
 [  22.  105.]
 [  22.  126.]
 [  22.  147.]
 [  22.  168.]
 [  22.  189.]
 [  22.  210.]
 [  22.  231.]
 [  22.  252.]
 [  22.  273.]
 [  22.  294.]
 [  22.  315.]
 [  22.  336.]
 [  22.  357.]
 [  22.  378.]
 [  22.  399.]
 [  22.  420.]
 [  22.  441.]
 [  22.  462.]
 [  22.  483.]
 [  22.  504.]
 [  22.  525.]
 [  22.  546.]
 [  22.  567.]
 [  22.  588.]
 [  22.  609.]
 [  22.  630.]
 [  22.  651.]
 [  22.  672.]
 [  22.  693.]
 [  22.  714.]
 [  22.  735.]
 [  22.  756.]
 [  22.  777.]
 [  22.  798.]
 [  22.  819.]
 [  22.  840.]
 [  22.  861.]
 [  22.  882.]
 [  22.  903.]
 [  22.  924.]
 [  22.  945.]
 [  22.  966.]
 [  22.  987.]
 [  22. 1008.]
 [  22. 1029.]
 [  22. 1050.]
 [  22. 1071.]
 [  22. 1092.]
 [  22. 1113.]
 [  22. 1134.]
 [  22. 1155.]
 [  22. 1176.]
 [  22. 1197.]
 [  22. 1218.]
 [  22. 1239.]
 [  22. 1260.]
 [  22. 1281.]
 [  22. 1302.]
 [  22. 1323.]
 [  22. 1344.]
 [  22. 1365.]
 [  22. 1386.]
 [  22. 1407.]
 [  22. 14

In [147]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0]


In [148]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  22.0


In [227]:
# Solve using simulated annealing - attempt 3 (population size 40, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=40, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[ 24.  82.]
 [ 24. 123.]
 [ 24. 164.]
 [ 24. 205.]
 [ 24. 246.]
 [ 24. 287.]
 [ 24. 328.]
 [ 24. 369.]
 [ 24. 410.]
 [ 24. 451.]]


In [150]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0]


In [151]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  24.0


In [228]:
# Solve using simulated annealing - attempt 4 (population size 100, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=100, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[  26.  202.]
 [  29.  304.]
 [  29.  405.]
 [  29.  506.]
 [  29.  607.]
 [  29.  708.]
 [  29.  809.]
 [  29.  910.]
 [  29. 1011.]
 [  29. 1112.]]


In [153]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [154]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  29.0


In [229]:
# Solve using simulated annealing - attempt 5 (population size 200, maximum 100 attempts, maximum 100 iterations)
init_state = np.zeros(DIMENSIONS)
best_state, best_fitness, fitness_curve = mlrose_hiive.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=10, max_iters=10, curve=True, random_state=1)
print(fitness_curve)

[[  24.  402.]
 [  25.  604.]
 [  26.  806.]
 [  28. 1008.]
 [  28. 1209.]
 [  29. 1411.]
 [  29. 1612.]
 [  29. 1813.]
 [  29. 2014.]
 [  29. 2215.]]


In [156]:
print('The best state found is: ', best_state)

The best state found is:  [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [157]:
print('The fitness at the best state is: ', best_fitness)

The fitness at the best state is:  29.0
